### ISSUE TITLE
Cannot build: missing dependency header

### ISSUE THREAD

**Issue by RReverser** [colmnet/ragel#1]
When trying to build, during the compilation I'm getting:

> reducer.cc:23:16: fatal error: if.h: No such file or directory

This seems to be introduced recently and doesn't happen with Ragel 7 from http://www.colm.net/open-source/ragel/.

**Comment by colmnet** [comment]
Pushed a fix.

**Comment by RReverser** [comment]
This happens during `make install`:

```
[dirname]/ragel/deps/colm-0.13.0.2/src/colm -c -o parse.c -e if.h -x if.cc -m commit.cc rlparse.lm
error: colm: -m is an invalid argument
error: colm: more than one input file name was given
make[2]: *** [parse.c] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

**Comment by colmnet** [comment]
Can you get the latest colm out of the github repos?

**Comment by RReverser** [comment]
Will do. So far used the latest release from the website.

**Comment by RReverser** [comment]
And now can't build it either, fails during configure stage:

```
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:63: error: required file '../../ltmain.sh' not found
```

**Comment by colmnet** [comment]
Do you run ./autogen.sh or some other command? ltmain.sh should be copied in from an absolute path location, not two levels up.

**Comment by RReverser** [comment]
Yes, that's exactly what I'm getting from `./autogen.sh`, sorry for confusion.

**Comment by colmnet** [comment]
I'm confused about where that path is coming from.

**Comment by RReverser** [comment]
Yeah, me too :/

**Comment by colmnet** [comment]
Next thing to look at would be the automake, libtool and autoconf versions you have installed.

Also, maybe you checked out ragel inside another project tree and libtool is confused by that?

**Comment by RReverser** [comment]
> Next thing to look at would be the automake, libtool and autoconf versions you have installed.

Installed latest from apt-get on Debian 8 (can't look atm, that's on another computer).

> Also, maybe you checked out ragel inside another project tree and libtool is confused by that?

Hm, no, not for ragel. But I checked out colm into subfolder of ragel (`deps/colm`), although don't really understand why libtool would be confused by it...

**Comment by RReverser** [comment]
@colmnet Yeah, moved it out of Ragel's folder and it worked. Weird why does it care...

**Comment by colmnet** [comment]
Likely wants to integrate itself into the larger project. Have access to that project's libraries, or provide it's own libraries to the larger project.

**Comment by RReverser** [comment]
Probably. Anyway, thanks, builds now, so can submit PR.

**Comment by RReverser** [comment]
Getting this again with latest master.

**Comment by colmnet** [comment]
rm parse.c

**Comment by colmnet** [comment]
Actually is a problem with libtool and the way I've done built sources. Will provide a fix.

**Comment by scottidler** [comment]
This is still an issue for 7.0.0.8.  Is there a work around until a fix happens?
