### ISSUE TITLE
Tokenizer and when conditions

### ISSUE THREAD

**Issue by RReverser** [colmnet/ragel#11]
I believe I asked about whether tokenizer can work with semantic conditions about half of a year ago, and you replied

> [@RReverser intended to work together](https://twitter.com/ehdtee/status/656557024206000130)

but got beaten by it again - not sure whether a bug or designed to work this way (in that case, would appreciate any advice).

I'm trying to design a tokenizer that enters certain tokens only on specific actions. In a simplest form:

```
%%{
    machine test;
    
    action permit12 { permit12 }
    action forbid12 { !permit12 }
    
    main := |*
        '1' when permit12 '2';
        '1' when forbid12;
    *|;
}%%
```

However, such tokenizer refuses to tokenize anything (neither `1` nor `12`) when `permit12` is falsy, and can tokenize only `12` when `permit12` is truthy.

Here is it's graph:

![test](https://cloud.githubusercontent.com/assets/557590/13985300/e60cf4a6-f0f3-11e5-8c16-8f0bbc5f89c9.png)

Which confirms my observations - for some reason, tokenizer created final states which can't be left, and the only path that points back to the tokenization is `1 (permit12, !forbid12) -> 2`. It's also unclear to me why it uses both conditions on paths where only one condition was written, thus creating impossible paths (such as `1 (permit12, forbid12) -> ...`).

I tried to rewrite it to use condition on entire token (even though it's not what I originally wanted), but that doesn't help either:

```
%%{
    machine test;
    
    action permit12 { permit12 }
    action forbid12 { !permit12 }
    
    main := |*
        '12' when permit12;
        '1' when forbid12;
    *|;
}%%
```

![test](https://cloud.githubusercontent.com/assets/557590/13985472/d068bda0-f0f4-11e5-89e8-31ed319c360b.png)

The only difference is that `2` is now also checked for `permit12` (which is always true in our case if it was reached at all), but same problems persist.

Could you please advise on what I'm doing wrong / what is the proper way of using semantic conditions on enter in tokenizer.

---

**UPD**: not really, see below for another update.

P.S. In this simplified case the obvious workaround would be to use condition on `2` instead:

```
%%{
    machine test;
    
    action permit12 { permit12 }
    action forbid12 { !permit12 }
    
    main := |*
        '1' '2' when permit12;
        '1';
    *|;
}%%
```

which works:

![test](https://cloud.githubusercontent.com/assets/557590/13985643/dc51c750-f0f5-11e5-9312-0c794836fe97.png)

but in real scanners the second part of the token is much more complex, and I would rather not add conditions on every possible continuation, but put it on this very beginning of the token in order to keep code simple and easy to read.

---

P.P.S. Actually that one doesn't work either, as it allows `1` even when `permit12` is truthy, which is not the same as original tokenizer (**only** `12` should be allowed in that case).

**Comment by colmnet** [comment]
Found the issue. Some of the scanner code was not appropriately renovated when the ragel 7 conditions were implemented. Will fix asap.

**Comment by RReverser** [comment]
Awesome, thank you!

**Comment by colmnet** [comment]
Just pushed a fix.
