### ISSUE TITLE
Colm backend: Parse error when using "access"

### ISSUE THREAD

**Issue by RReverser** [colmnet/ragel#21]
A simple example:

```ragel
%%{
    machine temp;

    access state->;

    part2 := "abc";

    main := 'xyz' @{ fnext part2; };

    write exec;
}%%
```

I'm trying to compile this code with Colm backend (either via `--colm-backend` or just by using a destination language where it's a default) and getting `temp.ri:82:49: parse error` with the following temporary representation:

```c
...
	st_case_3:
	if ( ( deref( data, p )) == 122 ) {
		goto ctr3;
	}
	{
		goto st0;
	}
	ctr3:
	host( "-", 1 ) @{state.}@ -> cs = 7;
	host( "temp.rl", 8 ) ${ host( "-", 1 ) @{state./* error here */}@ -> cs = 4;}$
	
	goto _again;
	st7:
	p+= 1;
	if ( p == pe )
	goto _test_eof7;
...
```

Same happens if using `access state.;` or even `variable cs state->cs;` etc. I did a quick look at `rlhc-host.lm`, but it seems to have `->` and `.` properly defined, so not yet sure why this happens.

@colmnet any ideas?

**Comment by colmnet** [comment]
Cannot reproduce.
