### ISSUE TITLE
Direct backend ignores -L option

### ISSUE THREAD

**Issue by RReverser** [colmnet/ragel#22]
Direct backend (default for C) ignores `-L` option and inserts `#line` directives unconditionally.

The reason I found this was actually another bug - it inserts those as `#line 4 "<internal>"` instead of actual filename for chunks that were inserted from `include`-d sources (and not from the original file), so GDB/LLDB can't show the real code.

**Comment by RReverser** [comment]
I also tried to switch to Colm backend, and it worked well until got yet another issue https://github.com/colmnet/ragel/issues/21.

*beta-tester problems :)*

**Comment by colmnet** [comment]
fixed (will come to github soon)
