### ISSUE TITLE
"could not find machine" when includes contain cross-references

### ISSUE THREAD

**Issue by RReverser** [colmnet/ragel#23]
Consider following sample:

```ragel
# c/actions.rl:
%%{
    machine test;

    action dosmth {

    }
}%%

# common/syntax.rl:
%%{
    machine test;

    something = 'something' @dosmth;
}%%

# main-c.rl:
%%{
    machine test;

    include 'c/actions.rl';
    include 'common/syntax.rl';

    main := something;
}%%
```

Such structure is convenient for having syntax description with named action references in one file, and language-specific actions in another file, and later including both in main executable in order.

It works well with Ragel 6 as well as until recent changes with development branch of Ragel 7, but doesn't work on `master` anymore, getting "main-c.rl: could not find machine test in common/syntax.rl" error.

**Comment by colmnet** [comment]
should be fixed on master now
