### ISSUE TITLE
Broken hex sequences support

### ISSUE THREAD

**Issue by RReverser** [colmnet/ragel#9]
Minimalistic test case:
```
USP = 0x12 0x34..0x56;
```

On the `master` branch, Ragel started throwing a `parse error` at `2:16` (pointing to `..` after `0x34`).

This seems to be introduced by https://github.com/colmnet/ragel/commit/41fcecbbe5f1bd0fc32125810410249fbdd23f40 (commit right before that works).

**Comment by colmnet** [comment]
Just pushed  a fix. Realize now this can't be done at the lexical level. Needs to happen at the parser level.

**Comment by RReverser** [comment]
Thanks!
